"""JsonSchemaAdapter — adapter over a raw JSON Schema dict.

The escape hatch. When a user has a schema that isn't a Python type (it came from
an OpenAPI spec, was generated by a sibling service, or describes a shape they
don't want to mirror in code), they should still be able to declare it as the
agent's output. This adapter takes the dict *verbatim* and returns ``dict``
instances on parse — no type stamping.

``jsonschema`` is OPTIONAL: when installed we do a real validation pass on
parse; when not, we settle for "is it a dict?" Either way the call site sees
the same :class:`OutputCoercionError` for failures, so the retry middleware
doesn't need to special-case this adapter."""

from __future__ import annotations

import json
from typing import Any

from agentkit.capabilities.output_schema.protocol import OutputCoercionError


class JsonSchemaAdapter:
    """Adapter over a raw JSON Schema dict. ``python_type`` is ``dict`` because
    that *is* the type instances are coerced into — there is no Python class
    associated with the schema."""

    python_type: type = dict
    """Always ``dict`` — the raw-schema flavour deliberately does not stamp a
    Python class. Callers who want a typed result should use one of the other
    adapters."""

    def __init__(self, schema: dict[str, Any], *, name: str | None = None) -> None:
        if not isinstance(schema, dict):
            raise TypeError(f"JsonSchemaAdapter expects a dict, got {type(schema).__name__}")
        if schema.get("type") != "object":
            # We could in principle support top-level arrays / primitives, but
            # provider structured-output modes universally expect an object at
            # the top level — refusing here surfaces the mismatch at build time.
            raise TypeError(
                "JsonSchemaAdapter requires a top-level object schema "
                "(`type: 'object'`); other top-level types are not supported"
            )
        self._schema = schema
        self.name: str = name or schema.get("title") or "Output"
        """Defaults to the schema's ``title`` if present, else a bland ``"Output"``
        — raw dicts have no class name to fall back on, so the caller is
        encouraged to pass ``name=`` when registering one."""

    def json_schema(self) -> dict[str, Any]:
        """Pass-through. We don't copy because the schema is treated as
        owned-by-caller; the adapter is just a thin handle around it."""
        return self._schema

    def parse(self, raw: str | dict[str, Any]) -> dict[str, Any]:
        """JSON-decode if needed, then *optionally* validate against the schema
        via the ``jsonschema`` library. The library import is local so this
        module loads on a box without it; absence is silently tolerated (we
        still enforce "is a dict")."""
        if isinstance(raw, str):
            try:
                payload = json.loads(raw)
            except json.JSONDecodeError as e:
                raise OutputCoercionError(
                    f"response is not valid JSON: {e.msg} (line {e.lineno}, col {e.colno})",
                    raw=raw,
                    errors=[f"json: {e.msg}"],
                ) from e
        else:
            payload = raw
        if not isinstance(payload, dict):
            raise OutputCoercionError(
                f"expected a JSON object for {self.name}, got {type(payload).__name__}",
                raw=raw,
                errors=[f"top-level: expected object, got {type(payload).__name__}"],
            )
        try:
            import jsonschema  # type: ignore[import-untyped]
        except ImportError:
            # Library not installed — we accept the dict as-is. The structured-
            # output mode on the provider side is the second line of defence.
            return payload
        try:
            jsonschema.validate(instance=payload, schema=self._schema)
        except jsonschema.ValidationError as e:
            path = ".".join(str(p) for p in e.absolute_path) or "<root>"
            raise OutputCoercionError(
                f"response failed schema validation at {path}: {e.message}",
                raw=raw,
                errors=[f"{path}: {e.message}"],
            ) from e
        return payload

    def partial_parse(self, raw: str) -> dict[str, Any] | None:
        """Tolerant parse → return the partial dict as-is.

        No further coercion is done — the raw-schema flavour returns
        ``dict`` instances on full parse, and the same convention
        applies mid-stream. Schema validation is intentionally skipped
        on the partial: a half-streamed object would routinely violate
        ``required``, and the strict terminal parse is the source of
        truth for conformance.
        """
        from agentkit.capabilities.output_schema._partial_json import parse_partial

        try:
            data = parse_partial(raw)
        except Exception:
            return None
        if not isinstance(data, dict):
            return None
        return data

    def serialize(self, value: dict[str, Any]) -> dict[str, Any]:
        """Identity — the value already IS the dict. Returned as-is rather than
        deep-copied because the durable store treats serialized output as
        owned-by-store after the call returns."""
        return value

    def validate(self, value: Any) -> dict[str, Any]:
        """Validate an arbitrary Python value against the raw JSON Schema.

        The raw-schema flavour has no Python class to ``isinstance``-check
        against, so the only fast-path is "already a dict". When ``jsonschema``
        is installed we run the same validation pass as :meth:`parse` so a
        non-conforming dict is rejected; without the library we accept any
        dict (consistent with ``parse``'s degradation mode). Anything that is
        not a dict raises :class:`OutputCoercionError`."""
        if not isinstance(value, dict):
            raise OutputCoercionError(
                f"value of type {type(value).__name__} is not a JSON object for {self.name}",
                raw=repr(value),
                errors=[f"top-level: expected object, got {type(value).__name__}"],
            )
        try:
            import jsonschema
        except ImportError:
            return value
        try:
            jsonschema.validate(instance=value, schema=self._schema)
        except jsonschema.ValidationError as e:
            path = ".".join(str(p) for p in e.absolute_path) or "<root>"
            raise OutputCoercionError(
                f"value failed schema validation at {path}: {e.message}",
                raw=value,
                errors=[f"{path}: {e.message}"],
            ) from e
        return value
